export interface ChatbotRulePreset {
  mot_cle: string;
  diagnostic: string;
  gravite: string;
  cout_min: number | null;
  cout_max: number | null;
  besoin_prestataire: boolean;
  categorie: string;
  actif: boolean;
}

export const CHATBOT_RULE_PRESETS: ChatbotRulePreset[] = [
  {
    mot_cle: 'surchauffe moteur',
    diagnostic: 'Le circuit de refroidissement est probablement en cause (radiateur, liquide ou thermostat).',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 950,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'voyant temperature allume',
    diagnostic: 'Le moteur chauffe anormalement. Arrêtez le véhicule et contrôlez le niveau de liquide de refroidissement.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'fuite liquide refroidissement',
    diagnostic: 'Une durite, le radiateur ou la pompe à eau peut fuir.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'batterie faible',
    diagnostic: 'La batterie est probablement déchargée ou en fin de vie.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 450,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'voiture ne demarre pas',
    diagnostic: 'Problème possible de batterie, démarreur ou alimentation électrique.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 1100,
    besoin_prestataire: true,
    categorie: 'Démarrage',
    actif: true,
  },
  {
    mot_cle: 'demarreur claque',
    diagnostic: 'Le démarreur ou le relais de démarrage peut être défectueux.',
    gravite: 'Élevée',
    cout_min: 180,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Démarrage',
    actif: true,
  },
  {
    mot_cle: 'alternateur hs',
    diagnostic: 'L’alternateur ne recharge probablement plus correctement la batterie.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 1300,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'voyant batterie',
    diagnostic: 'Défaut de charge électrique probable (alternateur, courroie ou batterie).',
    gravite: 'Moyenne',
    cout_min: 90,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'frein mou',
    diagnostic: 'Le circuit de freinage peut manquer de liquide ou présenter de l’air dans le circuit.',
    gravite: 'Élevée',
    cout_min: 90,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'bruit freinage',
    diagnostic: 'Plaquettes ou disques de frein usés possibles.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 1000,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'pedale frein dure',
    diagnostic: 'Le servofrein ou la dépression de freinage peut être défaillant.',
    gravite: 'Élevée',
    cout_min: 150,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'abs allume',
    diagnostic: 'Capteur ABS ou calculateur ABS potentiellement en défaut.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 950,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'pneu creve',
    diagnostic: 'Pneu percé ou jante endommagée.',
    gravite: 'Moyenne',
    cout_min: 30,
    cout_max: 450,
    besoin_prestataire: true,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'pression pneu basse',
    diagnostic: 'Perte de pression progressive possible (valve, crevaison lente).',
    gravite: 'Faible',
    cout_min: 20,
    cout_max: 250,
    besoin_prestataire: false,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'direction vibre',
    diagnostic: 'Équilibrage, parallélisme ou usure de suspension possible.',
    gravite: 'Moyenne',
    cout_min: 70,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Direction',
    actif: true,
  },
  {
    mot_cle: 'volant dur',
    diagnostic: 'Assistance de direction défaillante possible (pompe, fuite ou crémaillère).',
    gravite: 'Élevée',
    cout_min: 140,
    cout_max: 1700,
    besoin_prestataire: true,
    categorie: 'Direction',
    actif: true,
  },
  {
    mot_cle: 'clim ne refroidit pas',
    diagnostic: 'Manque de gaz, compresseur ou fuite sur le circuit de climatisation.',
    gravite: 'Faible',
    cout_min: 90,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'mauvaise odeur clim',
    diagnostic: 'Filtre habitacle encrassé ou évaporateur contaminé.',
    gravite: 'Faible',
    cout_min: 40,
    cout_max: 350,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'fumee blanche',
    diagnostic: 'Possible joint de culasse ou présence de liquide de refroidissement dans la chambre de combustion.',
    gravite: 'Élevée',
    cout_min: 350,
    cout_max: 3200,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'fumee noire',
    diagnostic: 'Combustion trop riche possible (injection, filtre à air, débitmètre).',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 1400,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'consommation carburant elevee',
    diagnostic: 'Mauvais réglage moteur ou capteurs défectueux possibles.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 1100,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'moteur broute',
    diagnostic: 'Ratés d’allumage ou problème d’injection possibles.',
    gravite: 'Moyenne',
    cout_min: 90,
    cout_max: 1300,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'perte puissance',
    diagnostic: 'Turbo, injection, admission ou échappement peuvent être en cause.',
    gravite: 'Élevée',
    cout_min: 140,
    cout_max: 2400,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'voyant moteur',
    diagnostic: 'Un défaut moteur est détecté par l’ECU. Un diagnostic valise est recommandé.',
    gravite: 'Moyenne',
    cout_min: 40,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Électronique',
    actif: true,
  },
  {
    mot_cle: 'boite vitesse bloquee',
    diagnostic: 'Défaut de boîte de vitesses (embrayage, synchros ou commande) possible.',
    gravite: 'Élevée',
    cout_min: 220,
    cout_max: 3500,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'embrayage patine',
    diagnostic: 'Disque d’embrayage usé probable.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'vitesses craquent',
    diagnostic: 'Problème d’embrayage ou de synchronisation de boîte.',
    gravite: 'Moyenne',
    cout_min: 180,
    cout_max: 2600,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'bruit suspension',
    diagnostic: 'Amortisseurs, coupelles ou silentblocs possiblement usés.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 1600,
    besoin_prestataire: true,
    categorie: 'Suspension',
    actif: true,
  },
  {
    mot_cle: 'voiture tire a droite',
    diagnostic: 'Parallélisme ou pression pneus à vérifier en priorité.',
    gravite: 'Moyenne',
    cout_min: 60,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Train roulant',
    actif: true,
  },
  {
    mot_cle: 'essuie glace ne marche pas',
    diagnostic: 'Moteur d’essuie-glace, relais ou fusible probablement défectueux.',
    gravite: 'Faible',
    cout_min: 40,
    cout_max: 450,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'phares faibles',
    diagnostic: 'Batterie faible, alternateur ou masse électrique à contrôler.',
    gravite: 'Faible',
    cout_min: 30,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Éclairage',
    actif: true,
  },
  {
    mot_cle: 'fuite huile',
    diagnostic: 'Joint moteur ou carter potentiellement en fuite.',
    gravite: 'Moyenne',
    cout_min: 90,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Lubrification',
    actif: true,
  },
  {
    mot_cle: 'fuite carburant',
    diagnostic: 'Fuite sur le circuit carburant, intervention rapide nécessaire.',
    gravite: 'Élevée',
    cout_min: 130,
    cout_max: 1400,
    besoin_prestataire: true,
    categorie: 'Carburant',
    actif: true,
  },
  {
    mot_cle: 'odeur essence',
    diagnostic: 'Possible fuite ou défaut d’étanchéité du circuit d’alimentation.',
    gravite: 'Élevée',
    cout_min: 90,
    cout_max: 1100,
    besoin_prestataire: true,
    categorie: 'Carburant',
    actif: true,
  },
  {
    mot_cle: 'turbo siffle',
    diagnostic: 'Usure turbo ou fuite sur le circuit de suralimentation possible.',
    gravite: 'Élevée',
    cout_min: 220,
    cout_max: 2800,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'chaine distribution bruit',
    diagnostic: 'La chaîne/courroie de distribution peut être détendue ou usée.',
    gravite: 'Élevée',
    cout_min: 300,
    cout_max: 2600,
    besoin_prestataire: true,
    categorie: 'Distribution',
    actif: true,
  },
  {
    mot_cle: 'courroie accessoire siffle',
    diagnostic: 'Courroie accessoires usée ou galet tendeur fatigué.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Distribution',
    actif: true,
  },
  {
    mot_cle: 'capteur stationnement ne marche pas',
    diagnostic: 'Un capteur de recul ou le faisceau associé est probablement défaillant.',
    gravite: 'Faible',
    cout_min: 60,
    cout_max: 500,
    besoin_prestataire: true,
    categorie: 'Électronique',
    actif: true,
  },
  {
    mot_cle: 'airbag allume',
    diagnostic: 'Défaut détecté sur le système SRS (airbag/pretensionneur/capteur).',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Sécurité',
    actif: true,
  },
  {
    mot_cle: 'verrouillage centralise hs',
    diagnostic: 'Moteur de serrure, clé ou module de centralisation à contrôler.',
    gravite: 'Faible',
    cout_min: 70,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Confort',
    actif: true,
  },
  {
    mot_cle: 'vitre electrique bloquee',
    diagnostic: 'Moteur de lève-vitre ou mécanisme de câble probablement défectueux.',
    gravite: 'Faible',
    cout_min: 80,
    cout_max: 600,
    besoin_prestataire: true,
    categorie: 'Confort',
    actif: true,
  },
  {
    mot_cle: 'echappement bruyant',
    diagnostic: 'Fuite ou corrosion sur la ligne d’échappement possible.',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 1400,
    besoin_prestataire: true,
    categorie: 'Échappement',
    actif: true,
  },
  {
    mot_cle: 'filtre particule encrasse',
    diagnostic: 'Le FAP peut être saturé, une régénération ou intervention est nécessaire.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 2200,
    besoin_prestataire: true,
    categorie: 'Échappement',
    actif: true,
  },
  {
    mot_cle: 'capot ne ferme pas',
    diagnostic: 'Mécanisme de verrouillage du capot à régler ou remplacer.',
    gravite: 'Faible',
    cout_min: 40,
    cout_max: 300,
    besoin_prestataire: true,
    categorie: 'Carrosserie',
    actif: true,
  },
  {
    mot_cle: 'bruit roulement roue',
    diagnostic: 'Un roulement de roue usé est probable.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Train roulant',
    actif: true,
  },
  {
    mot_cle: 'pedale embrayage molle',
    diagnostic: 'Circuit hydraulique d’embrayage ou mécanisme interne possiblement défectueux.',
    gravite: 'Élevée',
    cout_min: 150,
    cout_max: 1700,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
];
