export const CHATBOT_RULE_PRESETS = [
  {
    mot_cle: 'batterie faible',
    diagnostic: 'Batterie faible ou en fin de vie.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 350,
    besoin_prestataire: true,
    categorie: 'Électricien auto',
    actif: true,
  },
  {
    mot_cle: 'voiture ne démarre pas',
    diagnostic: 'Problème possible de batterie, démarreur ou alternateur.',
    gravite: 'Élevée',
    cout_min: 150,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Électricien auto',
    actif: true,
  },
  {
    mot_cle: 'voyant moteur',
    diagnostic: 'Anomalie détectée au niveau du moteur ou du système électronique.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 600,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'fumée blanche',
    diagnostic: 'Possible problème de joint de culasse ou infiltration de liquide de refroidissement.',
    gravite: 'Élevée',
    cout_min: 300,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'fumée noire',
    diagnostic: 'Mauvaise combustion, filtre à air encrassé ou problème d’injection.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'fumée bleue',
    diagnostic: 'Consommation anormale d’huile moteur ou usure interne du moteur.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 1600,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'moteur chauffe',
    diagnostic: 'Surchauffe moteur liée au radiateur, thermostat, ventilateur ou liquide de refroidissement.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'fuite eau',
    diagnostic: 'Possible fuite du radiateur, d’une durite ou du circuit de refroidissement.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 600,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'fuite huile',
    diagnostic: 'Fuite possible au niveau du carter, joint moteur ou filtre à huile.',
    gravite: 'Moyenne',
    cout_min: 70,
    cout_max: 500,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'frein faible',
    diagnostic: 'Usure des plaquettes, problème de liquide de frein ou disque endommagé.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 600,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'bruit frein',
    diagnostic: 'Plaquettes de frein usées ou disque de frein endommagé.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 500,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'pédale frein dure',
    diagnostic: 'Problème possible du servofrein ou du circuit de freinage.',
    gravite: 'Élevée',
    cout_min: 150,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'pneu crevé',
    diagnostic: 'Pneu perforé ou perte de pression importante.',
    gravite: 'Moyenne',
    cout_min: 20,
    cout_max: 250,
    besoin_prestataire: true,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'voiture tire à droite',
    diagnostic: 'Problème possible de parallélisme, pneus ou suspension.',
    gravite: 'Moyenne',
    cout_min: 60,
    cout_max: 400,
    besoin_prestataire: true,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'volant tremble',
    diagnostic: 'Équilibrage des roues, pneus usés ou problème de suspension.',
    gravite: 'Moyenne',
    cout_min: 40,
    cout_max: 400,
    besoin_prestataire: true,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'voiture tremble',
    diagnostic: 'Vibration liée aux pneus, supports moteur, suspension ou transmission.',
    gravite: 'Moyenne',
    cout_min: 70,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'bruit moteur',
    diagnostic: 'Bruit anormal pouvant venir de la courroie, distribution, soupapes ou roulements.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'claquement moteur',
    diagnostic: 'Possible problème de distribution, injecteurs, soupapes ou manque d’huile.',
    gravite: 'Élevée',
    cout_min: 200,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'perte puissance',
    diagnostic: 'Possible problème de turbo, injection, filtre à carburant ou capteur moteur.',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'consomme beaucoup',
    diagnostic: 'Surconsommation liée à l’injection, filtre à air, bougies ou sonde lambda.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'boite vitesse dure',
    diagnostic: 'Problème possible d’embrayage, huile de boîte ou synchronisation.',
    gravite: 'Moyenne',
    cout_min: 150,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'embrayage patine',
    diagnostic: 'Embrayage usé ou disque d’embrayage en fin de vie.',
    gravite: 'Élevée',
    cout_min: 400,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'vitesse ne passe pas',
    diagnostic: 'Problème d’embrayage, boîte de vitesses ou tringlerie.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'clim ne marche pas',
    diagnostic: 'Manque de gaz, compresseur défectueux ou fuite du circuit de climatisation.',
    gravite: 'Faible',
    cout_min: 80,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'clim chaud',
    diagnostic: 'Climatisation inefficace, recharge gaz ou compresseur à vérifier.',
    gravite: 'Faible',
    cout_min: 80,
    cout_max: 600,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'phare ne marche pas',
    diagnostic: 'Ampoule grillée, fusible ou problème électrique.',
    gravite: 'Faible',
    cout_min: 20,
    cout_max: 250,
    besoin_prestataire: true,
    categorie: 'Électricien auto',
    actif: true,
  },
  {
    mot_cle: 'essuie glace ne marche pas',
    diagnostic: 'Moteur d’essuie-glace, fusible ou commodo défectueux.',
    gravite: 'Moyenne',
    cout_min: 40,
    cout_max: 350,
    besoin_prestataire: true,
    categorie: 'Électricien auto',
    actif: true,
  },
  {
    mot_cle: 'alternateur',
    diagnostic: 'Alternateur défectueux, batterie non rechargée correctement.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Électricien auto',
    actif: true,
  },
  {
    mot_cle: 'odeur essence',
    diagnostic: 'Possible fuite de carburant ou problème d’injection.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'odeur brûlé',
    diagnostic: 'Possible surchauffe, embrayage usé, frein bloqué ou problème électrique.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'suspension bruit',
    diagnostic: 'Amortisseurs, rotules ou silentblocs probablement usés.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'voiture saute',
    diagnostic: 'Suspension ou amortisseurs fatigués.',
    gravite: 'Moyenne',
    cout_min: 150,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'échappement bruit',
    diagnostic: 'Silencieux, ligne d’échappement ou catalyseur endommagé.',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'airbag voyant',
    diagnostic: 'Défaut du système airbag ou capteur de sécurité.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'abs voyant',
    diagnostic: 'Défaut du système ABS ou capteur de roue.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 650,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'turbo siffle',
    diagnostic: 'Turbo, durite d’air ou fuite de pression à contrôler.',
    gravite: 'Élevée',
    cout_min: 200,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'radiateur',
    diagnostic: 'Radiateur encrassé, percé ou problème de refroidissement.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'courroie distribution',
    diagnostic: 'Courroie de distribution usée ou à remplacer rapidement.',
    gravite: 'Élevée',
    cout_min: 350,
    cout_max: 1300,
    besoin_prestataire: true,
    categorie: 'Mécanicien',
    actif: true,
  },
  {
    mot_cle: 'carrosserie rayée',
    diagnostic: 'Rayure ou dommage esthétique de carrosserie.',
    gravite: 'Faible',
    cout_min: 80,
    cout_max: 800,
    besoin_prestataire: true,
    categorie: 'Tôlier',
    actif: true,
  },
  {
    mot_cle: 'pare choc cassé',
    diagnostic: 'Pare-chocs endommagé nécessitant réparation ou remplacement.',
    gravite: 'Moyenne',
    cout_min: 150,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Tôlier',
    actif: true,
  },
];