export interface ChatbotRulePreset {
  mot_cle: string;
  diagnostic: string;
  gravite: string;
  cout_min: number | null;
  cout_max: number | null;
  besoin_prestataire: boolean;
  categorie: string;
  actif: boolean;
}

export const CHATBOT_RULE_PRESETS: ChatbotRulePreset[] = [
  {
    mot_cle: 'voiture ne demarre pas',
    diagnostic: 'Problème possible de batterie, démarreur, alternateur ou alimentation électrique.',
    gravite: 'Élevée',
    cout_min: 80,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Démarrage',
    actif: true,
  },
  {
    mot_cle: 'batterie faible',
    diagnostic: 'La batterie est probablement déchargée ou en fin de vie.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 450,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'voyant batterie',
    diagnostic: 'Défaut de charge électrique possible : alternateur, courroie ou batterie.',
    gravite: 'Moyenne',
    cout_min: 90,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'alternateur',
    diagnostic: 'L’alternateur peut ne plus recharger correctement la batterie.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 1300,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'demarreur claque',
    diagnostic: 'Le démarreur ou son relais peut être défectueux.',
    gravite: 'Élevée',
    cout_min: 180,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Démarrage',
    actif: true,
  },
  {
    mot_cle: 'moteur chauffe',
    diagnostic: 'Le circuit de refroidissement est probablement en cause : radiateur, thermostat, pompe à eau ou liquide de refroidissement.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 950,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'surchauffe moteur',
    diagnostic: 'Le moteur chauffe anormalement. Risque important de détérioration moteur.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'fuite liquide refroidissement',
    diagnostic: 'Fuite possible au niveau du radiateur, d’une durite, de la pompe à eau ou du vase d’expansion.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Refroidissement',
    actif: true,
  },
  {
    mot_cle: 'fumee blanche',
    diagnostic: 'Possible joint de culasse ou présence de liquide de refroidissement dans la combustion.',
    gravite: 'Élevée',
    cout_min: 350,
    cout_max: 3200,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'fumee noire',
    diagnostic: 'Combustion trop riche possible : injecteurs, filtre à air, débitmètre ou vanne EGR.',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 1400,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'fumee bleue',
    diagnostic: 'Consommation d’huile moteur possible : segmentation, turbo ou joints de soupapes.',
    gravite: 'Élevée',
    cout_min: 300,
    cout_max: 3000,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'perte puissance',
    diagnostic: 'Problème possible de turbo, injection, admission, filtre à carburant ou échappement.',
    gravite: 'Élevée',
    cout_min: 140,
    cout_max: 2400,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'moteur broute',
    diagnostic: 'Ratés d’allumage ou problème d’injection possibles.',
    gravite: 'Moyenne',
    cout_min: 90,
    cout_max: 1300,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'voyant moteur',
    diagnostic: 'Anomalie moteur détectée. Un diagnostic électronique est recommandé.',
    gravite: 'Moyenne',
    cout_min: 60,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'huile moteur',
    diagnostic: 'Niveau d’huile faible ou fuite possible. Risque d’usure moteur.',
    gravite: 'Élevée',
    cout_min: 50,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'fuite huile',
    diagnostic: 'Fuite possible au niveau du carter, joint moteur, filtre à huile ou turbo.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'bruit moteur',
    diagnostic: 'Bruit anormal moteur : courroie, distribution, soupapes ou support moteur possibles.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 2500,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'bruit freinage',
    diagnostic: 'Plaquettes ou disques de frein probablement usés.',
    gravite: 'Élevée',
    cout_min: 120,
    cout_max: 1000,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'frein mou',
    diagnostic: 'Circuit de freinage possiblement défaillant : air dans le circuit ou manque de liquide.',
    gravite: 'Élevée',
    cout_min: 90,
    cout_max: 700,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'pedale frein dure',
    diagnostic: 'Servofrein ou système d’assistance au freinage possiblement défaillant.',
    gravite: 'Élevée',
    cout_min: 150,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'abs allume',
    diagnostic: 'Capteur ABS ou calculateur ABS potentiellement en défaut.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 950,
    besoin_prestataire: true,
    categorie: 'Freinage',
    actif: true,
  },
  {
    mot_cle: 'embrayage patine',
    diagnostic: 'Disque d’embrayage probablement usé.',
    gravite: 'Élevée',
    cout_min: 400,
    cout_max: 1800,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'vitesse difficile',
    diagnostic: 'Problème possible de boîte de vitesses, embrayage ou tringlerie.',
    gravite: 'Moyenne',
    cout_min: 150,
    cout_max: 2500,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'boite vitesse bruit',
    diagnostic: 'Usure possible de boîte de vitesses ou manque d’huile de transmission.',
    gravite: 'Élevée',
    cout_min: 300,
    cout_max: 3500,
    besoin_prestataire: true,
    categorie: 'Transmission',
    actif: true,
  },
  {
    mot_cle: 'pneu creve',
    diagnostic: 'Pneu percé ou jante endommagée.',
    gravite: 'Moyenne',
    cout_min: 30,
    cout_max: 450,
    besoin_prestataire: true,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'pression pneu basse',
    diagnostic: 'Perte de pression progressive possible : valve, crevaison lente ou jante.',
    gravite: 'Faible',
    cout_min: 20,
    cout_max: 250,
    besoin_prestataire: false,
    categorie: 'Pneumatique',
    actif: true,
  },
  {
    mot_cle: 'direction vibre',
    diagnostic: 'Équilibrage, parallélisme, pneu déformé ou suspension usée possibles.',
    gravite: 'Moyenne',
    cout_min: 70,
    cout_max: 900,
    besoin_prestataire: true,
    categorie: 'Direction',
    actif: true,
  },
  {
    mot_cle: 'volant dur',
    diagnostic: 'Assistance de direction défaillante possible : pompe, fuite ou crémaillère.',
    gravite: 'Élevée',
    cout_min: 140,
    cout_max: 1700,
    besoin_prestataire: true,
    categorie: 'Direction',
    actif: true,
  },
  {
    mot_cle: 'suspension bruit',
    diagnostic: 'Amortisseur, silentbloc ou rotule possiblement usé.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Suspension',
    actif: true,
  },
  {
    mot_cle: 'clim ne refroidit pas',
    diagnostic: 'Manque de gaz, fuite ou compresseur de climatisation défaillant.',
    gravite: 'Faible',
    cout_min: 90,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'mauvaise odeur clim',
    diagnostic: 'Filtre habitacle encrassé ou évaporateur contaminé.',
    gravite: 'Faible',
    cout_min: 40,
    cout_max: 350,
    besoin_prestataire: true,
    categorie: 'Climatisation',
    actif: true,
  },
  {
    mot_cle: 'phare ne fonctionne pas',
    diagnostic: 'Ampoule, fusible, relais ou problème électrique possible.',
    gravite: 'Faible',
    cout_min: 20,
    cout_max: 300,
    besoin_prestataire: false,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'essuie glace ne marche pas',
    diagnostic: 'Moteur d’essuie-glace, fusible ou commodo possiblement défectueux.',
    gravite: 'Moyenne',
    cout_min: 40,
    cout_max: 500,
    besoin_prestataire: true,
    categorie: 'Électrique',
    actif: true,
  },
  {
    mot_cle: 'airbag allume',
    diagnostic: 'Défaut airbag ou prétensionneur détecté. Diagnostic électronique nécessaire.',
    gravite: 'Moyenne',
    cout_min: 80,
    cout_max: 1200,
    besoin_prestataire: true,
    categorie: 'Diagnostic électronique',
    actif: true,
  },
  {
    mot_cle: 'turbo siffle',
    diagnostic: 'Turbo, durite d’admission ou fuite de pression possible.',
    gravite: 'Élevée',
    cout_min: 250,
    cout_max: 3000,
    besoin_prestataire: true,
    categorie: 'Moteur',
    actif: true,
  },
  {
    mot_cle: 'injecteur',
    diagnostic: 'Injecteur encrassé ou défaillant possible.',
    gravite: 'Moyenne',
    cout_min: 120,
    cout_max: 1600,
    besoin_prestataire: true,
    categorie: 'Injection',
    actif: true,
  },
  {
    mot_cle: 'odeur essence',
    diagnostic: 'Fuite de carburant ou problème d’injection possible. Risque important.',
    gravite: 'Élevée',
    cout_min: 100,
    cout_max: 1500,
    besoin_prestataire: true,
    categorie: 'Carburant',
    actif: true,
  },
  {
    mot_cle: 'echappement bruit',
    diagnostic: 'Silencieux, catalyseur ou ligne d’échappement probablement endommagé.',
    gravite: 'Moyenne',
    cout_min: 100,
    cout_max: 1400,
    besoin_prestataire: true,
    categorie: 'Échappement',
    actif: true,
  },
];